In [1]:
import pandas as pd
import datetime

This dataset represents secured vehicle loans

In [2]:
# Reading accepted data
df_lt = pd.read_csv('../../data/original/lt-vehicle-loan-default-prediction/train.csv', low_memory=False)

In [3]:
df_lt.shape

(233154, 41)

In [4]:
df_lt.head(3)

,UniqueID,disbursed_amount,asset_cost,ltv,branch_id,supplier_id,manufacturer_id,Current_pincode_ID,Date.of.Birth,Employment.Type,...,SEC.SANCTIONED.AMOUNT,SEC.DISBURSED.AMOUNT,PRIMARY.INSTAL.AMT,SEC.INSTAL.AMT,NEW.ACCTS.IN.LAST.SIX.MONTHS,DELINQUENT.ACCTS.IN.LAST.SIX.MONTHS,AVERAGE.ACCT.AGE,CREDIT.HISTORY.LENGTH,NO.OF_INQUIRIES,loan_default
0,420825,50578,58400,89.55,67,22807,45,1441,01-01-84,Salaried,...,0,0,0,0,0,0,0yrs 0mon,0yrs 0mon,0,0
1,537409,47145,65550,73.23,67,22807,45,1502,31-07-85,Self employed,...,0,0,1991,0,0,1,1yrs 11mon,1yrs 11mon,0,1
2,417566,53278,61360,89.63,67,22807,45,1497,24-08-85,Self employed,...,0,0,0,0,0,0,0yrs 0mon,0yrs 0mon,0,0

In [5]:
df_lt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 233154 entries, 0 to 233153
Data columns (total 41 columns):
 #   Column                               Non-Null Count   Dtype
---  ------                               --------------   -----
 0   UniqueID                             233154 non-null  int64
 1   disbursed_amount                     233154 non-null  int64
 2   asset_cost                           233154 non-null  int64
 3   ltv                                  233154 non-null  float64
 4   branch_id                            233154 non-null  int64
 5   supplier_id                          233154 non-null  int64
 6   manufacturer_id                      233154 non-null  int64
 7   Current_pincode_ID                   233154 non-null  int64
 8   Date.of.Birth                        233154 non-null  object
 9   Employment.Type                      225493 non-null  object
 10  DisbursalDate                        233154 non-null  object
 11  State_ID                             233154 non-null  int64
 12  Employee_code_ID                     233154 non-null  int64
 13  MobileNo_Avl_Flag                    233154 non-null  int64
 14  Aadhar_flag                          233154 non-null  int64
 15  PAN_flag                             233154 non-null  int64
 16  VoterID_flag                         233154 non-null  int64
 17  Driving_flag                         233154 non-null  int64
 18  Passport_flag                        233154 non-null  int64
 19  PERFORM_CNS.SCORE                    233154 non-null  int64
 20  PERFORM_CNS.SCORE.DESCRIPTION        233154 non-null  object
 21  PRI.NO.OF.ACCTS                      233154 non-null  int64
 22  PRI.ACTIVE.ACCTS                     233154 non-null  int64
 23  PRI.OVERDUE.ACCTS                    233154 non-null  int64
 24  PRI.CURRENT.BALANCE                  233154 non-null  int64
 25  PRI.SANCTIONED.AMOUNT                233154 non-null  int64
 26  PRI.DISBURSED.AMOUNT                 233154 non-null  int64
 27  SEC.NO.OF.ACCTS                      233154 non-null  int64
 28  SEC.ACTIVE.ACCTS                     233154 non-null  int64
 29  SEC.OVERDUE.ACCTS                    233154 non-null  int64
 30  SEC.CURRENT.BALANCE                  233154 non-null  int64
 31  SEC.SANCTIONED.AMOUNT                233154 non-null  int64
 32  SEC.DISBURSED.AMOUNT                 233154 non-null  int64
 33  PRIMARY.INSTAL.AMT                   233154 non-null  int64
 34  SEC.INSTAL.AMT                       233154 non-null  int64
 35  NEW.ACCTS.IN.LAST.SIX.MONTHS         233154 non-null  int64
 36  DELINQUENT.ACCTS.IN.LAST.SIX.MONTHS  233154 non-null  int64
 37  AVERAGE.ACCT.AGE                     233154 non-null  object
 38  CREDIT.HISTORY.LENGTH                233154 non-null  object
 39  NO.OF_INQUIRIES                      233154 non-null  int64
 40  loan_default                         233154 non-null  int64
dtypes: float64(1), int64(34), object(6)
memory usage: 72.9+ MB

In [6]:
df_lt.describe()

,UniqueID,disbursed_amount,asset_cost,ltv,branch_id,supplier_id,manufacturer_id,Current_pincode_ID,State_ID,Employee_code_ID,...,SEC.OVERDUE.ACCTS,SEC.CURRENT.BALANCE,SEC.SANCTIONED.AMOUNT,SEC.DISBURSED.AMOUNT,PRIMARY.INSTAL.AMT,SEC.INSTAL.AMT,NEW.ACCTS.IN.LAST.SIX.MONTHS,DELINQUENT.ACCTS.IN.LAST.SIX.MONTHS,NO.OF_INQUIRIES,loan_default
count,233154.000000,233154.000000,2.331540e+05,233154.000000,233154.000000,233154.000000,233154.000000,233154.000000,233154.000000,233154.000000,...,233154.000000,2.331540e+05,2.331540e+05,2.331540e+05,2.331540e+05,2.331540e+05,233154.000000,233154.000000,233154.000000,233154.000000
mean,535917.573376,54356.993528,7.586507e+04,74.746530,72.936094,19638.635035,69.028054,3396.880247,7.262243,1549.477148,...,0.007244,5.427793e+03,7.295923e+03,7.179998e+03,1.310548e+04,3.232684e+02,0.381833,0.097481,0.206615,0.217071
std,68315.693711,12971.314171,1.894478e+04,11.456636,69.834995,3491.949566,22.141304,2238.147502,4.482230,975.261278,...,0.111079,1.702370e+05,1.831560e+05,1.825925e+05,1.513679e+05,1.555369e+04,0.955107,0.384439,0.706498,0.412252
min,417428.000000,13320.000000,3.700000e+04,10.030000,1.000000,10524.000000,45.000000,1.000000,1.000000,1.000000,...,0.000000,-5.746470e+05,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000
25%,476786.250000,47145.000000,6.571700e+04,68.880000,14.000000,16535.000000,48.000000,1511.000000,4.000000,713.000000,...,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000
50%,535978.500000,53803.000000,7.094600e+04,76.800000,61.000000,20333.000000,86.000000,2970.000000,6.000000,1451.000000,...,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000
75%,595039.750000,60413.000000,7.920175e+04,83.670000,130.000000,23000.000000,86.000000,5677.000000,10.000000,2362.000000,...,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,1.999000e+03,0.000000e+00,0.000000,0.000000,0.000000,0.000000
max,671084.000000,990572.000000,1.628992e+06,95.000000,261.000000,24803.000000,156.000000,7345.000000,22.000000,3795.000000,...,8.000000,3.603285e+07,3.000000e+07,3.000000e+07,2.564281e+07,4.170901e+06,35.000000,20.000000,36.000000,1.000000

In [7]:
df_lt.isnull().sum().sort_values(ascending=False)

Employment.Type                        7661
UniqueID                                  0
SEC.SANCTIONED.AMOUNT                     0
PRI.OVERDUE.ACCTS                         0
PRI.CURRENT.BALANCE                       0
PRI.SANCTIONED.AMOUNT                     0
PRI.DISBURSED.AMOUNT                      0
SEC.NO.OF.ACCTS                           0
SEC.ACTIVE.ACCTS                          0
SEC.OVERDUE.ACCTS                         0
SEC.CURRENT.BALANCE                       0
SEC.DISBURSED.AMOUNT                      0
PRI.NO.OF.ACCTS                           0
PRIMARY.INSTAL.AMT                        0
SEC.INSTAL.AMT                            0
NEW.ACCTS.IN.LAST.SIX.MONTHS              0
DELINQUENT.ACCTS.IN.LAST.SIX.MONTHS       0
AVERAGE.ACCT.AGE                          0
CREDIT.HISTORY.LENGTH                     0
NO.OF_INQUIRIES                           0
PRI.ACTIVE.ACCTS                          0
PERFORM_CNS.SCORE.DESCRIPTION             0
disbursed_amount                          0
DisbursalDate                             0
asset_cost                                0
ltv                                       0
branch_id                                 0
supplier_id                               0
manufacturer_id                           0
Current_pincode_ID                        0
Date.of.Birth                             0
State_ID                                  0
PERFORM_CNS.SCORE                         0
Employee_code_ID                          0
MobileNo_Avl_Flag                         0
Aadhar_flag                               0
PAN_flag                                  0
VoterID_flag                              0
Driving_flag                              0
Passport_flag                             0
loan_default                              0
dtype: int64

There are 40 columns. We are keeping only those columns that are aligned with asset value and loan structure.
- disbursed_amount — loan amount
- asset_cost — proxy for the vehicle’s collateral value
- ltv — measures loan-to-value ratio
- Employment.Type — indicates borrower income stability
- PERFORM_CNS.SCORE — captures borrower credit quality.
- CREDIT.HISTORY.LENGTH — measures borrower credit maturity
- AVERAGE.ACCT.AGE — indicates credit stability
- NO.OF_INQUIRIES — indicates aggressive borrowing behavior
- DELINQUENT.ACCTS.IN.LAST.SIX.MONTHS — captures recent delinquency risk
- loan_default — target variable for default model
- PRI.NO.OF.ACCTS — count of accounts
- PRI.ACTIVE.ACCTS — count of active accounts
- PRI.OVERDUE.ACCTS — count of overdue accounts
- PRIMARY.INSTAL.AMT — installment
- NEW.ACCTS.IN.LAST.SIX.MONTHS — count of recent accounts

In [8]:
# Selected columns
selected_columns = [
    "disbursed_amount",
    "asset_cost",
    "ltv",
    "Employment.Type",
    "PERFORM_CNS.SCORE",
    "CREDIT.HISTORY.LENGTH",
    "AVERAGE.ACCT.AGE",
    "NO.OF_INQUIRIES",
    "DELINQUENT.ACCTS.IN.LAST.SIX.MONTHS",
    "loan_default",
    "PRI.NO.OF.ACCTS",
    "PRI.ACTIVE.ACCTS",
    "PRI.OVERDUE.ACCTS",
    "PRIMARY.INSTAL.AMT",
    "NEW.ACCTS.IN.LAST.SIX.MONTHS"
]

In [9]:
# Keep only selected columns
df_lt = df_lt[selected_columns]

In [10]:
df_lt.rename(columns={
    "loan_default": "target",
    "disbursed_amount": "loan_amount",
    "asset_cost": "vehicle_value",
    "PERFORM_CNS.SCORE": "credit_score",
    "PRI.NO.OF.ACCTS": "num_accounts",
    "PRI.ACTIVE.ACCTS": "active_accounts",
    "PRI.OVERDUE.ACCTS": "overdue_accounts",
    "PRIMARY.INSTAL.AMT": "installment",
    "NEW.ACCTS.IN.LAST.SIX.MONTHS": "recent_accounts",
    "DELINQUENT.ACCTS.IN.LAST.SIX.MONTHS": "delinquency",
    "NO.OF_INQUIRIES": "inquiries"
}, inplace=True)

In [11]:
df_lt.shape

(233154, 15)

In [12]:
df_lt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 233154 entries, 0 to 233153
Data columns (total 15 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   loan_amount            233154 non-null  int64
 1   vehicle_value          233154 non-null  int64
 2   ltv                    233154 non-null  float64
 3   Employment.Type        225493 non-null  object
 4   credit_score           233154 non-null  int64
 5   CREDIT.HISTORY.LENGTH  233154 non-null  object
 6   AVERAGE.ACCT.AGE       233154 non-null  object
 7   inquiries              233154 non-null  int64
 8   delinquency            233154 non-null  int64
 9   target                 233154 non-null  int64
 10  num_accounts           233154 non-null  int64
 11  active_accounts        233154 non-null  int64
 12  overdue_accounts       233154 non-null  int64
 13  installment            233154 non-null  int64
 14  recent_accounts        233154 non-null  int64
dtypes: float64(1), int64(11), object(3)
memory usage: 26.7+ MB

In [13]:
df_lt.describe()

,loan_amount,vehicle_value,ltv,credit_score,inquiries,delinquency,target,num_accounts,active_accounts,overdue_accounts,installment,recent_accounts
count,233154.000000,2.331540e+05,233154.000000,233154.000000,233154.000000,233154.000000,233154.000000,233154.000000,233154.000000,233154.000000,2.331540e+05,233154.000000
mean,54356.993528,7.586507e+04,74.746530,289.462994,0.206615,0.097481,0.217071,2.440636,1.039896,0.156549,1.310548e+04,0.381833
std,12971.314171,1.894478e+04,11.456636,338.374779,0.706498,0.384439,0.412252,5.217233,1.941496,0.548787,1.513679e+05,0.955107
min,13320.000000,3.700000e+04,10.030000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000
25%,47145.000000,6.571700e+04,68.880000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000
50%,53803.000000,7.094600e+04,76.800000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000
75%,60413.000000,7.920175e+04,83.670000,678.000000,0.000000,0.000000,0.000000,3.000000,1.000000,0.000000,1.999000e+03,0.000000
max,990572.000000,1.628992e+06,95.000000,890.000000,36.000000,20.000000,1.000000,453.000000,144.000000,25.000000,2.564281e+07,35.000000

In [14]:
df_lt.isnull().sum().sort_values(ascending=False)

Employment.Type          7661
loan_amount                 0
vehicle_value               0
ltv                         0
credit_score                0
CREDIT.HISTORY.LENGTH       0
AVERAGE.ACCT.AGE            0
inquiries                   0
delinquency                 0
target                      0
num_accounts                0
active_accounts             0
overdue_accounts            0
installment                 0
recent_accounts             0
dtype: int64

Modifying data type of columns and filling empty values

In [15]:
def convert_to_year(age):
    yrs = float(age.split("yrs")[0])
    mon = float(age.split("mon")[0].split()[-1])
    return yrs + mon/12

In [16]:
df_lt["Employment.Type"] = df_lt["Employment.Type"].fillna("Unknown")

df_lt["AVERAGE.ACCT.AGE"] = df_lt["AVERAGE.ACCT.AGE"].apply(convert_to_year)
df_lt["AVERAGE.ACCT.AGE"] = df_lt["AVERAGE.ACCT.AGE"].astype(int)

df_lt["CREDIT.HISTORY.LENGTH"] = df_lt["CREDIT.HISTORY.LENGTH"].apply(convert_to_year)
df_lt["CREDIT.HISTORY.LENGTH"] = df_lt["CREDIT.HISTORY.LENGTH"].astype(int)

# categorical variables
df_lt["Employment.Type"] = df_lt["Employment.Type"].astype("category")

In [17]:
df_lt.isnull().sum().sort_values(ascending=False)

loan_amount              0
vehicle_value            0
ltv                      0
Employment.Type          0
credit_score             0
CREDIT.HISTORY.LENGTH    0
AVERAGE.ACCT.AGE         0
inquiries                0
delinquency              0
target                   0
num_accounts             0
active_accounts          0
overdue_accounts         0
installment              0
recent_accounts          0
dtype: int64

In [18]:
df_lt.shape

(233154, 15)

In [19]:
df_lt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 233154 entries, 0 to 233153
Data columns (total 15 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   loan_amount            233154 non-null  int64
 1   vehicle_value          233154 non-null  int64
 2   ltv                    233154 non-null  float64
 3   Employment.Type        233154 non-null  category
 4   credit_score           233154 non-null  int64
 5   CREDIT.HISTORY.LENGTH  233154 non-null  int64
 6   AVERAGE.ACCT.AGE       233154 non-null  int64
 7   inquiries              233154 non-null  int64
 8   delinquency            233154 non-null  int64
 9   target                 233154 non-null  int64
 10  num_accounts           233154 non-null  int64
 11  active_accounts        233154 non-null  int64
 12  overdue_accounts       233154 non-null  int64
 13  installment            233154 non-null  int64
 14  recent_accounts        233154 non-null  int64
dtypes: category(1), float64(1), int64(13)
memory usage: 25.1 MB

In [20]:
df_lt.describe()

,loan_amount,vehicle_value,ltv,credit_score,CREDIT.HISTORY.LENGTH,AVERAGE.ACCT.AGE,inquiries,delinquency,target,num_accounts,active_accounts,overdue_accounts,installment,recent_accounts
count,233154.000000,2.331540e+05,233154.000000,233154.000000,233154.000000,233154.000000,233154.000000,233154.000000,233154.000000,233154.000000,233154.000000,233154.000000,2.331540e+05,233154.000000
mean,54356.993528,7.586507e+04,74.746530,289.462994,1.145629,0.522384,0.206615,0.097481,0.217071,2.440636,1.039896,0.156549,1.310548e+04,0.381833
std,12971.314171,1.894478e+04,11.456636,338.374779,2.266861,1.150054,0.706498,0.384439,0.412252,5.217233,1.941496,0.548787,1.513679e+05,0.955107
min,13320.000000,3.700000e+04,10.030000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000
25%,47145.000000,6.571700e+04,68.880000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000
50%,53803.000000,7.094600e+04,76.800000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000
75%,60413.000000,7.920175e+04,83.670000,678.000000,2.000000,1.000000,0.000000,0.000000,0.000000,3.000000,1.000000,0.000000,1.999000e+03,0.000000
max,990572.000000,1.628992e+06,95.000000,890.000000,39.000000,30.000000,36.000000,20.000000,1.000000,453.000000,144.000000,25.000000,2.564281e+07,35.000000

# Feature Engineering

Create Core Engineered Features

In [21]:
# Normalize Loan-to-Value
df_lt["ltv_norm"] = df_lt["ltv"] / 100

In [22]:
# Installment to Loan Ratio
df_lt["installment_ratio"] = df_lt["installment"] / df_lt["loan_amount"]

In [23]:
# Loan Size vs Asset
df_lt["loan_to_asset"] = df_lt["loan_amount"] / df_lt["vehicle_value"]

In [24]:
# Active Ratio
df_lt["active_ratio"] = df_lt["active_accounts"] / (df_lt["num_accounts"] + 1)

In [25]:
# Overdue Ratio
df_lt["overdue_ratio"] = df_lt["overdue_accounts"] / (df_lt["num_accounts"] + 1)

In [26]:
# Recent Credit Activity
df_lt["recent_ratio"] = df_lt["recent_accounts"] / (df_lt["num_accounts"] + 1)

In [27]:
# Normalize Credit Score
df_lt["credit_score_norm"] = df_lt["credit_score"] / 900

In [28]:
# Inquiry Intensity
df_lt["inquiry_intensity"] = df_lt["inquiries"] / (df_lt["num_accounts"] + 1)

In [29]:
# Convert to binary
df_lt["has_delinquency"] = (df_lt["delinquency"] > 0).astype(int)

In [30]:
df_lt["credit_history_length"] = df_lt["CREDIT.HISTORY.LENGTH"]
df_lt["avg_account_age"] = df_lt["AVERAGE.ACCT.AGE"]

In [31]:
# Drop Raw Redundant Columns

df_lt.drop(columns=[
    "CREDIT.HISTORY.LENGTH",
    "AVERAGE.ACCT.AGE",
    "ltv",
], inplace=True)

In [32]:
df_lt.head()
df_lt.describe()

,loan_amount,vehicle_value,credit_score,inquiries,delinquency,target,num_accounts,active_accounts,overdue_accounts,installment,...,installment_ratio,loan_to_asset,active_ratio,overdue_ratio,recent_ratio,credit_score_norm,inquiry_intensity,has_delinquency,credit_history_length,avg_account_age
count,233154.000000,2.331540e+05,233154.000000,233154.000000,233154.000000,233154.000000,233154.000000,233154.000000,233154.000000,2.331540e+05,...,233154.000000,233154.000000,233154.000000,233154.000000,233154.000000,233154.000000,233154.000000,233154.000000,233154.000000,233154.000000
mean,54356.993528,7.586507e+04,289.462994,0.206615,0.097481,0.217071,2.440636,1.039896,0.156549,1.310548e+04,...,0.254070,0.724581,0.183559,0.030334,0.071099,0.321626,0.076221,0.078039,1.145629,0.522384
std,12971.314171,1.894478e+04,338.374779,0.706498,0.384439,0.412252,5.217233,1.941496,0.548787,1.513679e+05,...,3.355414,0.113278,0.245350,0.101565,0.167335,0.375972,0.293192,0.268233,2.266861,1.150054
min,13320.000000,3.700000e+04,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,...,0.000000,0.094638,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,47145.000000,6.571700e+04,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,...,0.000000,0.665866,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,53803.000000,7.094600e+04,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,...,0.000000,0.742962,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,60413.000000,7.920175e+04,678.000000,0.000000,0.000000,0.000000,3.000000,1.000000,0.000000,1.999000e+03,...,0.037328,0.810319,0.400000,0.000000,0.000000,0.753333,0.000000,0.000000,2.000000,1.000000
max,990572.000000,1.628992e+06,890.000000,36.000000,20.000000,1.000000,453.000000,144.000000,25.000000,2.564281e+07,...,901.994653,0.937987,0.944444,0.928571,20.000000,0.988889,12.000000,1.000000,39.000000,30.000000

In [33]:
df_lt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 233154 entries, 0 to 233153
Data columns (total 23 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   loan_amount            233154 non-null  int64
 1   vehicle_value          233154 non-null  int64
 2   Employment.Type        233154 non-null  category
 3   credit_score           233154 non-null  int64
 4   inquiries              233154 non-null  int64
 5   delinquency            233154 non-null  int64
 6   target                 233154 non-null  int64
 7   num_accounts           233154 non-null  int64
 8   active_accounts        233154 non-null  int64
 9   overdue_accounts       233154 non-null  int64
 10  installment            233154 non-null  int64
 11  recent_accounts        233154 non-null  int64
 12  ltv_norm               233154 non-null  float64
 13  installment_ratio      233154 non-null  float64
 14  loan_to_asset          233154 non-null  float64
 15  active_ratio           233154 non-null  float64
 16  overdue_ratio          233154 non-null  float64
 17  recent_ratio           233154 non-null  float64
 18  credit_score_norm      233154 non-null  float64
 19  inquiry_intensity      233154 non-null  float64
 20  has_delinquency        233154 non-null  int64
 21  credit_history_length  233154 non-null  int64
 22  avg_account_age        233154 non-null  int64
dtypes: category(1), float64(8), int64(14)
memory usage: 39.4 MB

In [34]:
df_lt["target"].value_counts()
df_lt["target"].value_counts(normalize=True)

target
0    0.782929
1    0.217071
Name: proportion, dtype: float64

In [35]:
df_lt.to_csv('../../data/processed/cleaned_lt-vehicle-loan_train.csv')